import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/react";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { VoucherProvider } from "@/context/VoucherContext";
import { Toaster } from "react-hot-toast";
import { AuthProvider } from "@/context/AuthContext";
import { SumProvider } from "@/context/SumContext";
import { ReturnVoucherProvider } from "@/context/ReturnVoucherContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Invoice Helper",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Analytics />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReturnVoucherProvider>
          <VoucherProvider>
            <AuthProvider>
              <SumProvider>
                <Header />
                {children}
                <Footer />
                <Toaster position="top-center" />
              </SumProvider>
            </AuthProvider>
          </VoucherProvider>
        </ReturnVoucherProvider>
      </body>
    </html>
  );
}
